[package]
name = "micro-timegrapher-studio"
version = "3.5.0"
description = "Enterprise Horological Acoustic Watch Diagnostic Workstation"
authors = ["Antigravity Horology Labs"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }
winres = "0.1"

[dependencies]
tauri = { version = "1.6.0", features = [ "shell-open", "dialog-all", "fs-all", "path-all", "protocol-asset" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
cpal = "0.15.2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
